{% set version = "11.0.2" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: ripgrep
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/ripgrep/archive/{{ version }}.tar.gz
  sha256: 0983861279936ada8bc7a6d5d663d590ad34eb44a44c75c2d6ccd0ab33490055

build:
  number: 0

requirements:
  build:
    - rust
    - binutils              # [linux]
    - {{native}}binutils    # [win]

test:
  commands:
    - rg --help

about:
  home: https://github.com/BurntSushi/ripgrep
  license: MIT
  summary: ripgrep recursively searches directories for a regex pattern
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
