{% set version = "12.0.0" %}

package:
  name: ripgrep
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/ripgrep/archive/{{ version }}.zip
  sha256: 389b6c9b68f073ea05d16168d9ead13b4ebd550873464494cdea9b787809d3df

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]

test:
  commands:
    - rg --help

about:
  home: https://github.com/BurntSushi/ripgrep
  license: MIT
  summary: ripgrep recursively searches directories for a regex pattern
  license_family: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
