{% set version = "15.2.0" %}

package:
  name: ripgrep
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/ripgrep/archive/{{ version }}.tar.gz
  sha256: 7605249d3eb0d5f170e3414498e3344e26b1e7a147aec518b57090b80036a562

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - asciidoctor                      # [not win]

test:
  commands:
    - rg --help

about:
  home: https://github.com/BurntSushi/ripgrep
  license: MIT
  summary: ripgrep recursively searches directories for a regex pattern
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
    - seanyen
