context:
  version: 15.2.0

package:
  name: ripgrep
  version: ${{ version }}

source:
  url: https://github.com/BurntSushi/ripgrep/archive/${{ version }}.tar.gz
  sha256: 7605249d3eb0d5f170e3414498e3344e26b1e7a147aec518b57090b80036a562

build:
  number: 0
  script: build

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - if: not win
      then: asciidoctor

tests:
  - package_contents:
      bin:
        - rg
      files:
        - if: unix
          then:
            - share/man/man1/rg.1
            - etc/bash_completion.d/rg
            - share/zsh/site-functions/_rg
  - script:
      - rg --help

about:
  homepage: https://github.com/BurntSushi/ripgrep
  repository: https://github.com/BurntSushi/ripgrep
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: ripgrep recursively searches directories for a regex pattern

extra:
  recipe-maintainers:
    - dbast
    - seanyen
